name: Lint and Test Project

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [develop]

jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: format:check
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:cov
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:e2e
